# Raw Materials

## Libraries

In [ ]:
import pandas as pd
import numpy as np

## DataSets

In [ ]:
cols = ['Fecha', 'Último', 'Apertura', 'Máximo', 'Mínimo', 'Vol.']

In [ ]:
df_gas = pd.read_csv('Datos históricos Futuros gas natural.csv', usecols = cols)
df_PetBrent = pd.read_csv('Datos históricos Futuros petróleo Brent.csv', usecols = cols)
df_Petcrude = pd.read_csv('Datos históricos Futuros petróleo crudo WTI.csv', usecols = cols)
df_Ur = pd.read_csv('Datos históricos Futuros uranio.csv', usecols = cols)
df_Coal = pd.read_excel('Coal_12_31_21-01_02_23 (CORREGIDO).xlsx')

In [ ]:
df_Coal = df_Coal[['Date', 'Close', 'Open', 'High', 'Low']]
df_Coal = df_Coal.rename(columns={'Date':'Fecha'})

In [ ]:
DataSets = [df_gas, df_PetBrent, df_Petcrude, df_Ur, df_Coal]
Column_names = ['Gas_Price', 'Gas_Open', 'Gas_High', 'Gas_Low', 'Gas_Vol.', 'PetBr_Price', 'PetBr_Open', 'PetBr_High', 'PetBr_Low', 'PetBr_Vol.', 'PetCr_Price', 'PetCr_Open', 'PetCr_High', 'PetCr_Low', 'PetCr_Vol.', 'Ur_Price', 'Ur_Open', 'Ur_High', 'Ur_Low', 'Ur_Vol.', 'Coal_Price', 'Coal_Open', 'Coal_High', 'Coal_Low']

In [ ]:
# dates to datetime.
for i in DataSets:
    i['Fecha'] = pd.to_datetime(i['Fecha'], format = '%d.%m.%Y')

## Concat with DateTime index.

In [ ]:
# Concat with datetime index.
dfs = [i.set_index('Fecha') for i in DataSets]
df = pd.concat(dfs, axis = 1)

In [ ]:
df.columns = Column_names

In [ ]:
df_Ur

         Fecha Último Apertura Máximo Mínimo Vol.
0   2023-02-27  51,05    51,05  51,05  51,05  NaN
1   2023-02-24  51,70    51,70  51,70  51,70  NaN
2   2023-02-23  51,80    51,80  51,80  51,80  NaN
3   2023-02-22  51,80    51,80  51,80  51,80  NaN
4   2023-02-21  51,80    51,80  51,80  51,80  NaN
..         ...    ...      ...    ...    ...  ...
455 2020-12-18  30,10    30,10  30,10  30,10  NaN
456 2020-12-17  30,10    30,10  30,10  30,10  NaN
457 2020-12-16  30,10    30,10  30,10  30,10  NaN
458 2020-12-15  30,10    30,10  30,10  30,10  NaN
459 2020-12-14  30,00    30,00  30,00  30,00  NaN

[460 rows x 6 columns]

## Dates range

In [ ]:
df = df.reset_index()

In [ ]:
df['Fecha'] = pd.to_datetime(df['Fecha'], dayfirst=True)

min_date = df['Fecha'].min()
max_date = df['Fecha'].max()

full_date_range = pd.date_range(start=min_date, end=max_date, freq='D')

missing_dates = full_date_range.difference(df['Fecha'])

print("Missing dates:", missing_dates)

Missing dates: DatetimeIndex(['2020-12-19', '2020-12-20', '2020-12-25', '2020-12-26',
               '2020-12-27', '2021-01-01', '2021-01-02', '2021-01-03',
               '2021-01-09', '2021-01-10',
               ...
               '2023-05-20', '2023-05-21', '2023-05-27', '2023-06-03',
               '2023-06-04', '2023-06-10', '2023-06-11', '2023-06-17',
               '2023-06-24', '2023-06-25'],
              dtype='datetime64[ns]', length=252, freq=None)

In [ ]:
date_df = pd.DataFrame({'Fecha': full_date_range})
merged_df = pd.merge(date_df, df, how='outer', on='Fecha')

In [ ]:
merged_df['Fecha'] = pd.to_datetime(merged_df['Fecha'], dayfirst=True)

min_date = merged_df['Fecha'].min()
max_date = merged_df['Fecha'].max()

full_date_range = pd.date_range(start=min_date, end=max_date, freq='D')

missing_dates = full_date_range.difference(merged_df['Fecha'])

print("Missing dates:", missing_dates)

Missing dates: DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [ ]:
merged_df = merged_df.sort_values(by='Fecha').reset_index(drop=True)

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 929 entries, 0 to 928
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        929 non-null    datetime64[ns]
 1   Gas_Price    662 non-null    object
 2   Gas_Open     662 non-null    object
 3   Gas_High     662 non-null    object
 4   Gas_Low      662 non-null    object
 5   Gas_Vol.     624 non-null    object
 6   PetBr_Price  646 non-null    object
 7   PetBr_Open   646 non-null    object
 8   PetBr_High   646 non-null    object
 9   PetBr_Low    646 non-null    object
 10  PetBr_Vol.   644 non-null    object
 11  PetCr_Price  664 non-null    object
 12  PetCr_Open   664 non-null    object
 13  PetCr_High   664 non-null    object
 14  PetCr_Low    664 non-null    object
 15  PetCr_Vol.   604 non-null    object
 16  Ur_Price     460 non-null    object
 17  Ur_Open      460 non-null    object
 18  Ur_High      460 non-null    object
 19  Ur_Low       460 non-null    object
 20  Ur_Vol.      14 non-null     object
 21  Coal_Price   644 non-null    float64
 22  Coal_Open    644 non-null    float64
 23  Coal_High    644 non-null    float64
 24  Coal_Low     644 non-null    float64
dtypes: datetime64[ns](1), float64(4), object(20)
memory usage: 181.6+ KB

In [ ]:
duplicate_dates_mask = merged_df.duplicated(subset=['Fecha'], keep=False)
duplicate_dates = merged_df[duplicate_dates_mask]
print(duplicate_dates)

Empty DataFrame
Columns: [Fecha, Gas_Price, Gas_Open, Gas_High, Gas_Low, Gas_Vol., PetBr_Price, PetBr_Open, PetBr_High, PetBr_Low, PetBr_Vol., PetCr_Price, PetCr_Open, PetCr_High, PetCr_Low, PetCr_Vol., Ur_Price, Ur_Open, Ur_High, Ur_Low, Ur_Vol., Coal_Price, Coal_Open, Coal_High, Coal_Low]
Index: []

[0 rows x 25 columns]

In [ ]:
print(merged_df['Fecha'].min())
print(merged_df['Fecha'].max())

2020-12-14 00:00:00
2023-06-30 00:00:00

## DataFrame Final (Cleaning).

In [ ]:
start_date = pd.Timestamp('2020-12-15 00:00:00')
end_date = pd.Timestamp('2023-05-01 00:00:00')
df_final = merged_df[(merged_df['Fecha'] >= start_date) & (merged_df['Fecha'] <= end_date)]

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 868 entries, 1 to 868
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        868 non-null    datetime64[ns]
 1   Gas_Price    616 non-null    object
 2   Gas_Open     616 non-null    object
 3   Gas_High     616 non-null    object
 4   Gas_Low      616 non-null    object
 5   Gas_Vol.     583 non-null    object
 6   PetBr_Price  602 non-null    object
 7   PetBr_Open   602 non-null    object
 8   PetBr_High   602 non-null    object
 9   PetBr_Low    602 non-null    object
 10  PetBr_Vol.   601 non-null    object
 11  PetCr_Price  618 non-null    object
 12  PetCr_Open   618 non-null    object
 13  PetCr_High   618 non-null    object
 14  PetCr_Low    618 non-null    object
 15  PetCr_Vol.   564 non-null    object
 16  Ur_Price     459 non-null    object
 17  Ur_Open      459 non-null    object
 18  Ur_High      459 non-null    object
 19  Ur_Low       459 non-null    object
 20  Ur_Vol.      14 non-null     object
 21  Coal_Price   600 non-null    float64
 22  Coal_Open    600 non-null    float64
 23  Coal_High    600 non-null    float64
 24  Coal_Low     600 non-null    float64
dtypes: datetime64[ns](1), float64(4), object(20)
memory usage: 176.3+ KB

In [ ]:
df_final['Gas_Vol.']

1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
        ...
864    105,22K
865    176,42K
866        NaN
867        NaN
868    108,99K
Name: Gas_Vol., Length: 868, dtype: object

In [ ]:
#Cleaning numbers.
def convert_to_float(x):
    if isinstance(x, str):
        return pd.to_numeric(x.replace(',', '.'), errors='coerce')
    return pd.to_numeric(x, errors='coerce')

# Cleaning volumes columns.
def clean_and_convert_volume(x):
    if isinstance(x, str):
        x = x.replace(',', '.').replace('K', '')
        return pd.to_numeric(x, errors='coerce') * 1000
    return x

In [ ]:
columns_to_convert = [
    'Gas_Price', 'Gas_Open', 'Gas_High', 'Gas_Low',
    'PetBr_Price', 'PetBr_Open', 'PetBr_High', 'PetBr_Low',
    'PetCr_Price', 'PetCr_Open', 'PetCr_High', 'PetCr_Low',
    'Ur_Price', 'Ur_Open', 'Ur_High', 'Ur_Low',
]

columns_to_convert_vol = ['PetCr_Vol.', 'Ur_Vol.', 'PetBr_Vol.', 'Gas_Vol.']

In [ ]:
for column in columns_to_convert:
    df_final[column] = df_final[column].apply(convert_to_float)

C:\Users\migue\AppData\Local\Temp\ipykernel_16516\2830322753.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[column] = df_final[column].apply(convert_to_float)

In [ ]:
for column in columns_to_convert_vol:
    df_final[column] = df_final[column].apply(clean_and_convert_volume)

C:\Users\migue\AppData\Local\Temp\ipykernel_16516\3082748756.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[column] = df_final[column].apply(clean_and_convert_volume)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 868 entries, 1 to 868
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        868 non-null    datetime64[ns]
 1   Gas_Price    616 non-null    float64
 2   Gas_Open     616 non-null    float64
 3   Gas_High     616 non-null    float64
 4   Gas_Low      616 non-null    float64
 5   Gas_Vol.     583 non-null    float64
 6   PetBr_Price  602 non-null    float64
 7   PetBr_Open   602 non-null    float64
 8   PetBr_High   602 non-null    float64
 9   PetBr_Low    602 non-null    float64
 10  PetBr_Vol.   601 non-null    float64
 11  PetCr_Price  618 non-null    float64
 12  PetCr_Open   618 non-null    float64
 13  PetCr_High   618 non-null    float64
 14  PetCr_Low    618 non-null    float64
 15  PetCr_Vol.   564 non-null    float64
 16  Ur_Price     459 non-null    float64
 17  Ur_Open      459 non-null    float64
 18  Ur_High      459 non-null    float64
 19  Ur_Low       459 non-null    float64
 20  Ur_Vol.      14 non-null     float64
 21  Coal_Price   600 non-null    float64
 22  Coal_Open    600 non-null    float64
 23  Coal_High    600 non-null    float64
 24  Coal_Low     600 non-null    float64
dtypes: datetime64[ns](1), float64(24)
memory usage: 176.3 KB

In [ ]:
df_gas

         Fecha Último Apertura Máximo Mínimo     Vol.
0   2023-06-30  2,798    2,675  2,825  2,640      NaN
1   2023-06-29  2,701    2,662  2,746  2,616  118,61K
2   2023-06-28  2,603    2,788  2,839  2,593    1,32K
3   2023-06-27  2,763    2,777  2,809  2,724   71,15K
4   2023-06-26  2,791    2,758  2,816  2,720   31,60K
..         ...    ...      ...    ...    ...      ...
657 2021-01-07  2,729    2,722  2,755  2,663  135,48K
658 2021-01-06  2,716    2,688  2,770  2,606  144,69K
659 2021-01-05  2,702    2,599  2,732  2,591  149,83K
660 2021-01-04  2,581    2,626  2,670  2,566  128,38K
661 2020-12-31  2,539    2,433  2,547  2,429  111,11K

[662 rows x 6 columns]

## Missing Values

In [ ]:
df_final

,Fecha,Gas_Price,Gas_Open,Gas_High,Gas_Low,Gas_Vol.,PetBr_Price,PetBr_Open,PetBr_High,PetBr_Low,...,PetCr_Vol.,Ur_Price,Ur_Open,Ur_High,Ur_Low,Ur_Vol.,Coal_Price,Coal_Open,Coal_High,Coal_Low
1,2020-12-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.1,30.1,30.1,30.1,NaN,NaN,NaN,NaN,NaN
2,2020-12-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.1,30.1,30.1,30.1,NaN,NaN,NaN,NaN,NaN
3,2020-12-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.1,30.1,30.1,30.1,NaN,NaN,NaN,NaN,NaN
4,2020-12-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.1,30.1,30.1,30.1,NaN,NaN,NaN,NaN,NaN
5,2020-12-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
864,2023-04-27,2.355,2.314,2.376,2.268,105220.0,78.37,77.77,78.61,77.39,...,345880.0,NaN,NaN,NaN,NaN,NaN,140.0,0.0,0.0,0.0
865,2023-04-28,2.410,2.358,2.529,2.285,176420.0,79.54,78.25,79.61,77.69,...,328400.0,NaN,NaN,NaN,NaN,NaN,136.4,0.0,0.0,0.0
866,2023-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
867,2023-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
868,2023-05-01,2.318,2.398,2.410,2.290,108990.0,79.31,80.11,80.24,78.13,...,215020.0,NaN,NaN,NaN,NaN,NaN,136.4,0.0,0.0,0.0

In [ ]:
df_final.set_index('Fecha', inplace=True)

In [ ]:
nan_rows = df_final[df_final.isnull().all(axis=1)]
nan_groups = nan_rows.groupby(pd.Grouper(freq='M')).size()
print(nan_groups)

Fecha
2020-12-31     5
2021-01-31    10
2021-02-28     7
2021-03-31     8
2021-04-30     9
2021-05-31     9
2021-06-30     8
2021-07-31     8
2021-08-31     9
2021-09-30     7
2021-10-31    10
2021-11-30     8
2021-12-31     8
2022-01-31     9
2022-02-28     7
2022-03-31     8
2022-04-30    10
2022-05-31     8
2022-06-30     7
2022-07-31     9
2022-08-31     8
2022-09-30     7
2022-10-31    10
2022-11-30     8
2022-12-31     7
2023-01-31     8
2023-02-28     7
2023-03-31     8
2023-04-30    11
Freq: M, dtype: int64

In [ ]:
df_final_fill = df_final.fillna(method='ffill', limit=3)
df_final_fill.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 868 entries, 2020-12-15 to 2023-05-01
Data columns (total 24 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gas_Price    852 non-null    float64
 1   Gas_Open     852 non-null    float64
 2   Gas_High     852 non-null    float64
 3   Gas_Low      852 non-null    float64
 4   Gas_Vol.     852 non-null    float64
 5   PetBr_Price  852 non-null    float64
 6   PetBr_Open   852 non-null    float64
 7   PetBr_High   852 non-null    float64
 8   PetBr_Low    852 non-null    float64
 9   PetBr_Vol.   852 non-null    float64
 10  PetCr_Price  852 non-null    float64
 11  PetCr_Open   852 non-null    float64
 12  PetCr_High   852 non-null    float64
 13  PetCr_Low    852 non-null    float64
 14  PetCr_Vol.   821 non-null    float64
 15  Ur_Price     676 non-null    float64
 16  Ur_Open      676 non-null    float64
 17  Ur_High      676 non-null    float64
 18  Ur_Low       676 non-null    float64
 19  Ur_Vol.      38 non-null     float64
 20  Coal_Price   852 non-null    float64
 21  Coal_Open    852 non-null    float64
 22  Coal_High    852 non-null    float64
 23  Coal_Low     852 non-null    float64
dtypes: float64(24)
memory usage: 169.5 KB

In [ ]:
df_Ur.shape

(460, 6)

In [ ]:
nan_rows = df_final.loc[df_final['Ur_Price'].isnull(), 'Ur_Price']
nan_groups = nan_rows.groupby(pd.Grouper(freq='M')).size()
print(nan_groups)

Fecha
2020-12-31     5
2021-01-31    12
2021-02-28     9
2021-03-31     8
2021-04-30     9
2021-05-31    11
2021-06-30     8
2021-07-31    10
2021-08-31     9
2021-09-30    12
2021-10-31    31
2021-11-30    30
2021-12-31    31
2022-01-31    25
2022-02-28     9
2022-03-31     8
2022-04-30    10
2022-05-31    23
2022-06-30     9
2022-07-31    11
2022-08-31     8
2022-09-30     9
2022-10-31    10
2022-11-30     9
2022-12-31    10
2023-01-31    11
2023-02-28    10
2023-03-31    31
2023-04-30    30
2023-05-31     1
Freq: M, Name: Ur_Price, dtype: int64

## To_Excel

In [ ]:
df_final_fill.head(30)

,Fecha,Gas_Price,Gas_Open,Gas_High,Gas_Low,Gas_Vol.,PetBr_Price,PetBr_Open,PetBr_High,PetBr_Low,...,PetCr_Vol.,Ur_Price,Ur_Open,Ur_High,Ur_Low,Ur_Vol.,Coal_Price,Coal_Open,Coal_High,Coal_Low
0,15-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.10,30.10,30.10,30.10,NaN,NaN,NaN,NaN,NaN
1,16-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.10,30.10,30.10,30.10,NaN,NaN,NaN,NaN,NaN
2,17-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.10,30.10,30.10,30.10,NaN,NaN,NaN,NaN,NaN
3,18-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.10,30.10,30.10,30.10,NaN,NaN,NaN,NaN,NaN
4,19-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.10,30.10,30.10,30.10,NaN,NaN,NaN,NaN,NaN
5,20-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.10,30.10,30.10,30.10,NaN,NaN,NaN,NaN,NaN
6,21-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.25,30.25,30.25,30.25,NaN,NaN,NaN,NaN,NaN
7,22-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.30,30.30,30.30,30.30,NaN,NaN,NaN,NaN,NaN
8,23-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.35,30.35,30.35,30.35,NaN,NaN,NaN,NaN,NaN
9,24-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.35,30.35,30.35,30.35,NaN,NaN,NaN,NaN,NaN
10,25-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.35,30.35,30.35,30.35,NaN,NaN,NaN,NaN,NaN
11,26-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.35,30.35,30.35,30.35,NaN,NaN,NaN,NaN,NaN
12,27-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.35,30.35,30.35,30.35,NaN,NaN,NaN,NaN,NaN
13,28-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.00,30.00,30.00,30.00,NaN,NaN,NaN,NaN,NaN
14,29-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.70,30.70,30.70,30.70,NaN,NaN,NaN,NaN,NaN
15,30-12-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.70,30.70,30.70,30.70,NaN,NaN,NaN,NaN,NaN
16,31-12-2020,2.539,2.433,2.547,2.429,111110.0,51.80,51.49,51.84,50.90,...,181890.0,30.70,30.70,30.70,30.70,NaN,69.00,0.00,0.00,0.00
17,01-01-2021,2.539,2.433,2.547,2.429,111110.0,51.80,51.49,51.84,50.90,...,181890.0,30.70,30.70,30.70,30.70,NaN,69.00,0.00,0.00,0.00
18,02-01-2021,2.539,2.433,2.547,2.429,111110.0,51.80,51.49,51.84,50.90,...,181890.0,30.70,30.70,30.70,30.70,NaN,69.00,0.00,0.00,0.00
19,03-01-2021,2.539,2.433,2.547,2.429,111110.0,51.80,51.49,51.84,50.90,...,181890.0,30.70,30.70,30.70,30.70,NaN,69.00,0.00,0.00,0.00
20,04-01-2021,2.581,2.626,2.670,2.566,128380.0,51.09,51.50,53.33,50.56,...,528530.0,30.85,30.85,30.85,30.85,NaN,69.30,69.75,70.25,69.75
21,05-01-2021,2.702,2.599,2.732,2.591,149830.0,53.60,50.95,53.90,50.70,...,643190.0,30.65,30.65,30.65,30.65,NaN,64.90,68.50,68.75,65.90
22,06-01-2021,2.716,2.688,2.770,2.606,144690.0,54.30,53.52,54.73,53.02,...,509370.0,30.65,30.65,30.65,30.65,NaN,64.25,65.75,65.75,64.20
23,07-01-2021,2.729,2.722,2.755,2.663,135480.0,54.38,54.13,54.90,53.94,...,369290.0,30.65,30.65,30.65,30.65,NaN,66.60,66.50,66.60,65.75
24,08-01-2021,2.700,2.675,2.730,2.626,148730.0,55.99,54.56,56.36,54.34,...,499420.0,30.60,30.60,30.60,30.60,NaN,68.50,67.75,68.50,67.35
25,09-01-2021,2.700,2.675,2.730,2.626,148730.0,55.99,54.56,56.36,54.34,...,499420.0,30.60,30.60,30.60,30.60,NaN,68.50,67.75,68.50,67.35
26,10-01-2021,2.700,2.675,2.730,2.626,148730.0,55.99,54.56,56.36,54.34,...,499420.0,30.60,30.60,30.60,30.60,NaN,68.50,67.75,68.50,67.35
27,11-01-2021,2.747,2.600,2.811,2.589,177250.0,55.66,56.24,56.39,54.99,...,394820.0,30.60,30.60,30.60,30.60,NaN,68.50,68.55,68.55,68.40
28,12-01-2021,2.753,2.794,2.899,2.718,201430.0,56.58,55.66,56.79,55.51,...,400200.0,30.60,30.60,30.60,30.60,NaN,70.50,69.10,70.50,68.95
29,13-01-2021,2.727,2.737,2.826,2.708,169240.0,56.06,56.83,57.42,55.77,...,429900.0,30.60,30.60,30.60,30.60,NaN,70.15,69.50,70.10,69.50

In [ ]:
df_final_fill = df_final_fill.reset_index()
df_final_fill['Fecha'] = df_final_fill['Fecha'].dt.strftime('%d-%m-%Y')

In [ ]:
name = 'RawMaterials.xlsx'

x = df_final_fill

x.to_excel(name, index=False)